# Generated by Django 3.0.2 on 2020-01-14 17:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 14, 17, 17, 6, 514763, tzinfo=utc)),
        ),
    ]
